### ISSUE TITLE
The dataset is a piece of shit.

### ISSUE THREAD

**Issue by zpge** [pranoyr/head-detection-using-yolo#13]
1. In the xml, the sizes of some images are 0,0.
2. Some labeled boxes have area of 0.

Totally a waste of my time.

**Comment by pranoyr** [comment]
You can ignore the bboxes which has 0,0 values. Didn't know your time was so valuable.

**Comment by yangyuke001** [comment]
@zpge Would you mind share me the annotion-files that the author provided,it's missing now.Thank you .

**Comment by zpge** [comment]
> You can ignore the bboxes which has 0,0 values. Didn't know your time was so valuable.

Really sorry. Just because I spent long time without figuring out the bug. Appreciate your contribution very much.

**Comment by yangyuke001** [comment]
@zpge Would you mind share me the annotion files that the author provided,it's missing now.Thank you very much.
