### ISSUE TITLE
Predictions missing on some frames ( overhead camera video) 

### ISSUE THREAD

**Issue by prashant-bansod** [pranoyr/head-detection-using-yolo#6]
@pranoyr Thank you very much for sharing your work. I have tested your implementation on some videos. The video was taken with the overhead camera. In these videos, some frames are missing the bounding boxes. Do you think this will work with the overhead camera videos? Do I need to finetune the model? If yes, do you have any advice for me? 
Thank you very much for your time. 

For your reference, the output of my sample video. [https://drive.google.com/open?id=1RvmSx721zZ-WoatilS_xN-dN_BbcCq9A](url)

**Comment by pranoyr** [comment]
Try training with the overhead images. Use yolov3 or retinanet for more
accuracy.

**Comment by prashant-bansod** [comment]
@pranoyr Thanks. I tried to look for the dataset with pictures taken from overhead camera. I could not find any such dataset. I would appreciate if you could share if there is any such dataset. Thanks a lot again.

**Comment by yangyuke001** [comment]
@prashant-bansod Would you mind share me the annotion-files that the author provided,it's missing now.Thank you .
